#- name: Install epel-release
#  yum:
#    name: epel-release
#    state: present
- name: Manually add EPEL repository for RHEL 9
  command:
    cmd: "dnf -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm"
  when: ansible_distribution_major_version == '9'

- name: Install Nginx
  yum:
    name: nginx
    state: present

- name: Start and enable Nginx
  service:
    name: nginx
    state: started
    enabled: yes
