name: Create S3 Bucket

on:
  workflow_dispatch: # 手動トリガー

jobs:
  create_bucket:
    runs-on: [self-hosted, Linux, X64]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.0

    - name: Prepare Terraform Local Backend
      run: |
        mv environments/dev/backend.tf environments/dev/backend.tf.backup  
        mv environments/dev/backend.local.tf environments/dev/backend.tf

    - name: Terraform Init
      run: |
        cd environments/dev
        terraform init

    - name: Terraform Apply
      run: |
        cd environments/dev
        terraform apply -auto-approve -target=module.s3_bucket

    - name: Switch to S3 Backend
      run: |
        mv environments/dev/backend.tf.backup environments/dev/backend.tf
        cd environments/dev
        terraform init -migrate-state
