name: Create S3 Bucket

on:
  workflow_dispatch: # 手動トリガー

jobs:
  create_bucket:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1  # 任意のリージョンを指定

    - name: Create S3 Bucket
      run: |
        # main.tf からバケット名を取得
        BUCKET_NAME=$(terraform -chdir=dev output -raw s3_bucket_name)
        aws s3api create-bucket --bucket $BUCKET_NAME --region ap-northeast-1 --create-bucket-configuration LocationConstraint=ap-northeast-1
        echo "BUCKET_NAME=${BUCKET_NAME}" >> $GITHUB_ENV
