name: Create S3 Bucket

on:
  workflow_dispatch: # 手動トリガー

jobs:
  create_bucket:
    runs-on: [self-hosted, Linux, X64]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1  # 任意のリージョンを指定

    - name: Terraform Init
      run: terraform init -reconfigure -backend-config=dev/backend.tf

    - name: Terraform Apply to create only the S3 bucket
      run: terraform apply -auto-approve -target=terraform.backend["s3"]

